### ISSUE TITLE
Symlinks page is empty and doesn't show existing symlinks

### ISSUE THREAD

**Issue by godfuture** [OpenMediaVault-Plugin-Developers/openmediavault-symlinks#1] opened 2018-04-18 00:05 UTC
I have created two symlinks within the plugin. But they disappeared and they are not displayed anymore.

OMV: 4.1.4.1
Kernel: 4.15.0.0-bpo

**Comment by ryecoaaron** [comment] 2018-04-18 11:32
What is the output of:   sudo omv-showkey symlinks

**Comment by godfuture** [comment] 2018-04-18 22:57
Both, _omv-showkey symlinks_ and _omv-showkey_ return no result.

**Comment by ryecoaaron** [comment] 2018-04-18 23:24
Nothing is being saved then.  Can you clear your browser cache and try creating a new symlink.  Let me know if you get any messages.

**Comment by godfuture** [comment] 2018-04-23 22:50
I cleared the browser cache and tried to create a new symlink:
`Fehler #0:
OMV\Config\DatabaseException: Failed to execute XPath query '//services/symlinks/symlinks'. in /usr/share/php/openmediavault/config/database.inc:244
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/symlinks.inc(83): OMV\Config\Database->set(Object(OMV\Config\ConfigObject))
#1 [internal function]: OMVRpcServiceSymlinks->setSymlink(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setSymlink', Array, Array)
#4 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Symlinks', 'setSymlink', Array, Array, 1)`

And "symlinks" does not exist in "/etc/openmediavault/config.xml".

**Comment by ryecoaaron** [comment] 2018-04-24 00:58
Sounds like the plugin isn't fully installed.  Post the output of: dpkg -l | grep openm

**Comment by godfuture** [comment] 2018-04-25 20:04
```
root@media-server:~# dpkg -l | grep openm
ii  openmediavault                   4.1.4-1                                 all          openmediavault - The open network attached storage solution
ii  openmediavault-backup            3.11                                    all          backup plugin for OpenMediaVault.
ii  openmediavault-diskstats         4.0.2-1                                 all          OpenMediaVault disk monitoring plugin
ii  openmediavault-docker-gui        4.0.1                                   all          OpenMediaVault plugin for Docker
ii  openmediavault-keyring           1.0                                     all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-letsencrypt       3.4.5                                   all          Generate free and valid SSL certificates for OMV
ii  openmediavault-luksencryption    3.0.3                                   all          OpenMediaVault LUKS encryption plugin
ii  openmediavault-lvm2              4.0.5-1                                 all          OpenMediaVault Logical Volume Manager (LVM2) plugin
ii  openmediavault-nginx             4.0.2                                   all          Nginx plugin for OpenMediaVault.
ii  openmediavault-omvextrasorg      4.1.3                                   all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-rsnapshot         4.1.3                                   all          OpenMediaVault rsnapshot backup plugin.
ii  openmediavault-symlinks          3.1.3                                   all          OpenMediaVault symlinks plugin
```
I have deinstalled openmediavault-symlinks, and installed right after. Then I have readded old symlinks in web gui:
```
Fehler #0:
OMV\Exception: Failed to create symbolic link at /home/test in /usr/share/openmediavault/engined/rpc/symlinks.inc:90
Stack trace:
#0 [internal function]: OMVRpcServiceSymlinks->setSymlink(Array, Array)
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setSymlink', Array, Array)
#3 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Symlinks', 'setSymlink', Array, Array, 1)
#4 {main}
```
Even the symlink already existed and readding failed with an error, it now appeared in web gui. When I try to delete it from there, it is still existant on filesystem:
```
root@media-server:~# ls -la /home
insgesamt 8
drwxr-xr-x  2 root root 4096 Apr 25 21:14 .
drwxr-xr-x 29 root root 4096 Apr 25 21:21 ..
lrwxrwxrwx  1 root root   32 Apr 25 21:14 test -> /srv/dev-disk-by-label-mypart
```

**Comment by ryecoaaron** [comment] 2018-04-25 20:58
Reinstalling the plugin fixed the database issue.  The error creating a new entry with an existing symlink was by design.  I have changed that is 3.1.4 in the repo now.  The delete bug has also been fixed in that release.

**Closed as completed by ryecoaaron** 2018-04-25 20:58 UTC
